name: chessboard
version: 0.0.1
author: Anders Forsell <aforsell1971@gmail.com>
description: chessboard.dart is derived from chessboard.js, but created as a Polymer element (web component) that provides an easy way to include a chessboard in a web application.
homepage: https://github.com/andersforsell/chessboard.dart
dependencies:
  chess: any
  core_elements: any
  paper_elements: any
  polymer: '>=0.11.0-dev.2 <0.12.0'
transformers:
- polymer:
    entry_points:
    - example/example.html
