name: chessboard
description: A sample Polymer application
dependencies:
  paper_elements: any
  polymer: '>=0.11.0-dev.2 <0.12.0'
dev_dependencies:
  chess:
    path: ../chess.dart
transformers:
- polymer:
    entry_points: web/test.html
