name: chessboard
version: 0.0.1
author: Anders Forsell <aforsell1971@gmail.com>
description: chessboard.dart is derived from chessboard.js, but created as a Polymer element (web component) that provides an easy way to include a chessboard in a web application.
homepage: https://github.com/andersforsell/chessboard.dart
dependencies:
  chess: '>=0.6.1 <0.7.0'
  core_elements: '>=0.0.6 <0.1.0'
  paper_elements: '>=0.0.1 <0.1.0'
  polymer: '>=0.11.0-dev.2 <0.12.0'
dev_dependencies:
  ghpages_generator: any
transformers:
- polymer:
    entry_points:
    - example/app.html
